# Generated by Django 6.0.2 on 2026-02-21 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='behaviour_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/'),
        ),
        migrations.AddField(
            model_name='student',
            name='marks_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
